# -*- coding: utf-8 -*-
"""untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Wariithi/3be43ec42787447d2a444cefeedff115/untitled1.ipynb
"""

# Ask user for their name
name = input("Enter your name: ")

# Ask user for their age
age = input("Enter your age: ")

# Ask user for their location
location = input("Enter your location: ")

# Print personalized message
print(f"Hello {name}, you are {age} years old and live in {location}.")